package xlog

import (
	"context"
)

// The ctxLogger type embeds the Logger interface and adds context, entries, and context handle fields.
type ctxLogger struct {
	Logger
	ctx       context.Context
	entries   map[string]any
	ctxHandle CtxHandle
}

// WithContext creates a new logger with the provided context and context handle.
// If handles is not provided, the default context handle is used.
func WithContext(logger Logger, ctx context.Context, handles ...CtxHandle) Logger {
	var handle CtxHandle
	if len(handles) > 0 {
		handle = handles[0]
	} else {
		handle = getDefCtxHandle()
	}
	return ctxLogger{
		Logger:    logger,
		ctx:       ctx,
		ctxHandle: handle,
	}
}

// WithEntries creates a new logger with the provided entries and an empty context.
func WithEntries(logger Logger, entries map[string]any) Logger {
	return ctxLogger{
		Logger:    logger,
		ctx:       context.Background(),
		entries:   entries,
		ctxHandle: emptyHandle,
	}
}

func (c ctxLogger) Log(opts ...LogOption) {
	opts = append(opts, WithCallerSkipOne, WithFields(c.buildFields()...))
	c.Logger.Log(opts...)
}

func (c ctxLogger) Fatal(a ...any) {
	if c.IsEnabled(FATAL) {
		c.Logger.Log(WithPrint(a...), withFatal, WithCallerSkipOne, WithFields(c.buildFields()...))
	}
}

func (c ctxLogger) Fatalf(format string, a ...any) {
	if c.IsEnabled(FATAL) {
		c.Logger.Log(WithPrintf(format, a...), withFatal, WithCallerSkipOne, WithFields(c.buildFields()...))
	}
}

func (c ctxLogger) Fatalw(msg string, fields ...Field) {
	if c.IsEnabled(FATAL) {
		c.Logger.Log(WithPrintMsg(msg), withFatal, WithCallerSkipOne, WithFields(c.buildFields(fields...)...))
	}
}

func (c ctxLogger) Error(a ...any) {
	if c.IsEnabled(ERROR) {
		c.Logger.Log(WithPrint(a...), withError, WithCallerSkipOne, WithFields(c.buildFields()...))
	}
}

func (c ctxLogger) Errorf(format string, a ...any) {
	if c.IsEnabled(ERROR) {
		c.Logger.Log(WithPrintf(format, a...), withError, WithCallerSkipOne, WithFields(c.buildFields()...))
	}
}

func (c ctxLogger) Errorw(msg string, fields ...Field) {
	if c.IsEnabled(ERROR) {
		c.Logger.Log(WithPrintMsg(msg), withError, WithCallerSkipOne, WithFields(c.buildFields(fields...)...))
	}
}

func (c ctxLogger) Warn(a ...any) {
	if c.IsEnabled(WARN) {
		c.Logger.Log(WithPrint(a...), withWarn, WithCallerSkipOne, WithFields(c.buildFields()...))
	}
}

func (c ctxLogger) Warnf(format string, a ...any) {
	if c.IsEnabled(WARN) {
		c.Logger.Log(WithPrintf(format, a...), withWarn, WithCallerSkipOne, WithFields(c.buildFields()...))
	}
}

func (c ctxLogger) Warnw(msg string, fields ...Field) {
	if c.IsEnabled(WARN) {
		c.Logger.Log(WithPrintMsg(msg), withWarn, WithCallerSkipOne, WithFields(c.buildFields(fields...)...))
	}
}

func (c ctxLogger) Info(a ...any) {
	if c.IsEnabled(INFO) {
		c.Logger.Log(WithPrint(a...), withInfo, WithCallerSkipOne, WithFields(c.buildFields()...))
	}
}

func (c ctxLogger) Infof(format string, a ...any) {
	if c.IsEnabled(INFO) {
		c.Logger.Log(WithPrintf(format, a...), withInfo, WithCallerSkipOne, WithFields(c.buildFields()...))
	}
}

func (c ctxLogger) Infow(msg string, fields ...Field) {
	if c.IsEnabled(INFO) {
		c.Logger.Log(WithPrintMsg(msg), withInfo, WithCallerSkipOne, WithFields(c.buildFields(fields...)...))
	}
}

func (c ctxLogger) Debug(a ...any) {
	if c.IsEnabled(DEBUG) {
		c.Logger.Log(WithPrint(a...), withDebug, WithCallerSkipOne, WithFields(c.buildFields()...))
	}
}

func (c ctxLogger) Debugf(format string, a ...any) {
	if c.IsEnabled(DEBUG) {
		c.Logger.Log(WithPrintf(format, a...), withDebug, WithCallerSkipOne, WithFields(c.buildFields()...))
	}
}

func (c ctxLogger) Debugw(msg string, fields ...Field) {
	if c.IsEnabled(DEBUG) {
		c.Logger.Log(WithPrintMsg(msg), withDebug, WithCallerSkipOne, WithFields(c.buildFields(fields...)...))
	}
}

// buildFields builds the final list of fields to be logged by appending
// the fields generated by the CtxHandle and the additional entries
// provided during context creation, to the fields passed as argument.
// If there are no additional entries, only the fields generated by the
// CtxHandle are appended. If there are additional entries, they are
// appended to the fields generated by the CtxHandle.
func (c ctxLogger) buildFields(fields ...Field) []Field {
	fields = append(fields, c.ctxHandle(c.ctx)...)
	if len(c.entries) > 0 {
		for key, entry := range c.entries {
			fields = append(fields, Field{Key: key, Value: entry})
		}
	}
	return fields
}
